# Generated by Django 3.2 on 2021-07-06 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EldhrimnirApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='carrera_seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seccion', models.IntegerField(unique=True)),
                ('date_edit', models.DateTimeField(blank=True)),
                ('carrera', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='EldhrimnirApp.carreras')),
                ('user_edit', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
