# Generated by Django 3.2 on 2021-07-06 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EldhrimnirApp', '0002_carrera_seccion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carrera_seccion',
            old_name='seccion',
            new_name='seccion_num',
        ),
    ]
