# Generated by Django 3.2 on 2021-08-04 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('EldhrimnirApp', '0004_materia_seccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='NivelesNum2',
            fields=[
                ('nivel_num', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('nom_nivel', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NivelUsu',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('nivel_usu', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='EldhrimnirApp.nivelesnum2')),
            ],
        ),
    ]
