# Generated by Django 3.2 on 2021-09-21 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EldhrimnirApp', '0007_materiasestu'),
    ]

    operations = [
        migrations.CreateModel(
            name='MateriaTeacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='EldhrimnirApp.materia_seccion')),
                ('profesor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
