# Generated by Django 3.2 on 2021-10-02 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EldhrimnirApp', '0008_materiateacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia_seccion',
            name='profesor',
        ),
    ]
