# Generated by Django 3.2 on 2021-10-11 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EldhrimnirApp', '0009_remove_materia_seccion_profesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Materia',
            fields=[
                ('id1', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Nombre', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Solo letras para el nombre por favor.', regex='^[a-zA-ZñáéíóúäëïöüÑàèìòù\\s]+$')])),
                ('num_eval_min', models.IntegerField()),
            ],
        ),
    ]
