# Generated by Django 3.2 on 2021-10-18 14:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EldhrimnirApp', '0011_materia_seccion_tipo_mate'),
    ]

    operations = [
        migrations.CreateModel(
            name='evaluacion_materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('ponderacion', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Ponderación no valida.'), django.core.validators.MaxValueValidator(100, message='Ponderación no valida.')])),
                ('fecha', models.DateTimeField(blank=True)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EldhrimnirApp.materia_seccion')),
            ],
        ),
    ]
