# Generated by Django 3.2 on 2021-10-31 11:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EldhrimnirApp', '0013_auto_20211026_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion_materia',
            name='ponderacion',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(5, message='Ponderación no valida.'), django.core.validators.MaxValueValidator(30, message='Ponderación no valida.')]),
        ),
    ]
