# Generated by Django 3.2 on 2021-11-01 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EldhrimnirApp', '0016_alter_materia_seccion_user_edit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluacion_materia',
            name='fecha',
            field=models.DateField(blank=True),
        ),
    ]
