# Generated by Django 3.2 on 2021-11-15 23:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EldhrimnirApp', '0020_rename_evaluacion_num_mate_eval_estudiante_evaluacion_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carreras',
            name='user_edit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
