# Generated by Django 3.2 on 2021-12-02 01:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EldhrimnirApp', '0021_alter_carreras_user_edit'),
    ]

    operations = [
        migrations.CreateModel(
            name='permisos_bd',
            fields=[
                ('id1', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Nombre', models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Solo letras para el nombre por favor.', regex='^[a-zA-ZñáéíóúäëïöüÑàèìòù\\s]+$')])),
                ('estado_perm', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='carrera_seccion',
            name='seccion_num',
            field=models.IntegerField(),
        ),
    ]
