# Generated by Django 3.2 on 2021-12-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EldhrimnirApp', '0022_auto_20211201_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia_seccion',
            name='materia_nom',
            field=models.CharField(max_length=200),
        ),
    ]
